// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.nulltest

data class Reading (
  val id: Long,
  val label: String,
  val countBig: Long?,
  val countInt: Int?,
  val countSmall: Short?,
  val ratio: Double?,
  val ratioReal: Float?,
  val enabled: Boolean?,
  val requiredBig: Long,
  val requiredFlag: Boolean
)

