// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.nulltest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

interface Queries {
  @Throws(SQLException::class)
  fun getReading(id: Long): Reading?

  @Throws(SQLException::class)
  fun listReadings(): List<Reading>

}

