// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.nulltest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

const val getReading = """-- name: getReading :one

SELECT id, label, count_big, count_int, count_small, ratio, ratio_real, enabled,
       required_big, required_flag
FROM readings
WHERE id = ?
"""

const val listReadings = """-- name: listReadings :many
SELECT id, label, count_big, count_int, count_small, ratio, ratio_real, enabled,
       required_big, required_flag
FROM readings
ORDER BY id
"""

class QueriesImpl(
  private val conn: Connection,
) : Queries {

// Read-only on purpose. The write path has its own, separate nullable-parameter bug
// (`stmt.setLong(i, x)` is emitted for a `Long?` parameter, which does not compile), so
// these queries only exercise the row-reading path this example is here to cover. The test
// seeds its rows with plain JDBC.

  @Throws(SQLException::class)
  override fun getReading(id: Long): Reading? {
    return conn.prepareStatement(getReading).use { stmt ->
      stmt.setLong(1, id)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Reading(
                results.getLong(1),
                results.getString(2),
                results.getLong(3).takeUnless { results.wasNull() },
                results.getInt(4).takeUnless { results.wasNull() },
                results.getShort(5).takeUnless { results.wasNull() },
                results.getDouble(6).takeUnless { results.wasNull() },
                results.getFloat(7).takeUnless { results.wasNull() },
                results.getBoolean(8).takeUnless { results.wasNull() },
                results.getLong(9),
                results.getBoolean(10)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun listReadings(): List<Reading> {
    return conn.prepareStatement(listReadings).use { stmt ->

      val results = stmt.executeQuery()
      val ret = mutableListOf<Reading>()
      while (results.next()) {
          ret.add(Reading(
                results.getLong(1),
                results.getString(2),
                results.getLong(3).takeUnless { results.wasNull() },
                results.getInt(4).takeUnless { results.wasNull() },
                results.getShort(5).takeUnless { results.wasNull() },
                results.getDouble(6).takeUnless { results.wasNull() },
                results.getFloat(7).takeUnless { results.wasNull() },
                results.getBoolean(8).takeUnless { results.wasNull() },
                results.getLong(9),
                results.getBoolean(10)
            ))
      }
      ret
    }
  }

}

