// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.jsontest

import com.example.jsontest.dto.Payload

data class Event (
  val id: Long,
  val name: String,
  val payload: Payload,
  val metadata: Payload?
)

