// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.jsontest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types

import com.example.jsontest.dto.Payload
import tools.jackson.databind.json.JsonMapper

const val createEvent = """-- name: createEvent :one
INSERT INTO events (name, payload, metadata)
VALUES (?, ?, ?)
RETURNING id, name, payload, metadata
"""

const val getEvent = """-- name: getEvent :one
SELECT id, name, payload, metadata FROM events
WHERE id = ? LIMIT 1
"""

const val listEvents = """-- name: listEvents :many
SELECT id, name, payload, metadata FROM events
ORDER BY id
"""

class QueriesImpl(
  private val conn: Connection,
  private val mapper: JsonMapper,
) : Queries {

  @Throws(SQLException::class)
  override fun createEvent(
      name: String,
      payload: Payload,
      metadata: Payload?): Event? {
    return conn.prepareStatement(createEvent).use { stmt ->
      stmt.setString(1, name)
          stmt.setObject(2, mapper.writeValueAsString(payload), Types.OTHER)
          stmt.setObject(3, metadata?.let { mapper.writeValueAsString(it) }, Types.OTHER)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Event(
                results.getLong(1),
                results.getString(2),
                mapper.readValue(results.getString(3), Payload::class.java),
                results.getString(4)?.let { mapper.readValue(it, Payload::class.java) }
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun getEvent(id: Long): Event? {
    return conn.prepareStatement(getEvent).use { stmt ->
      stmt.setLong(1, id)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Event(
                results.getLong(1),
                results.getString(2),
                mapper.readValue(results.getString(3), Payload::class.java),
                results.getString(4)?.let { mapper.readValue(it, Payload::class.java) }
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun listEvents(): List<Event> {
    return conn.prepareStatement(listEvents).use { stmt ->

      val results = stmt.executeQuery()
      val ret = mutableListOf<Event>()
      while (results.next()) {
          ret.add(Event(
                results.getLong(1),
                results.getString(2),
                mapper.readValue(results.getString(3), Payload::class.java),
                results.getString(4)?.let { mapper.readValue(it, Payload::class.java) }
            ))
      }
      ret
    }
  }

}

