// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.jsontest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types

import com.example.jsontest.dto.Payload
import tools.jackson.databind.json.JsonMapper

interface Queries {
  @Throws(SQLException::class)
  fun createEvent(
      name: String,
      payload: Payload,
      metadata: Payload?): Event?

  @Throws(SQLException::class)
  fun getEvent(id: Long): Event?

  @Throws(SQLException::class)
  fun listEvents(): List<Event>

  @Throws(SQLException::class)
  fun listEventsByIds(ids: List<Long>): List<Event>

}

