// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.numerictest

data class Ledger (
  val id: Long,
  val label: String,
  val amount: java.math.BigDecimal,
  val fee: java.math.BigDecimal?
)

