// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.numerictest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

const val createEntry = """-- name: createEntry :one
INSERT INTO ledger (label, amount, fee)
VALUES (?, ?, ?)
RETURNING id, label, amount, fee
"""

const val getEntry = """-- name: getEntry :one
SELECT id, label, amount, fee FROM ledger
WHERE id = ? LIMIT 1
"""

const val listEntries = """-- name: listEntries :many
SELECT id, label, amount, fee FROM ledger
ORDER BY id
"""

const val listEntriesByAmounts = """-- name: listEntriesByAmounts :many
SELECT id, label, amount, fee FROM ledger
WHERE amount IN (/*SLICE:amounts*/?)
ORDER BY id
"""

const val listEntriesOver = """-- name: listEntriesOver :many
SELECT id, label, amount, fee FROM ledger
WHERE amount > ?
ORDER BY id
"""

class QueriesImpl(
  private val conn: Connection,
) : Queries {

  @Throws(SQLException::class)
  override fun createEntry(
      label: String,
      amount: java.math.BigDecimal,
      fee: java.math.BigDecimal?): Ledger? {
    return conn.prepareStatement(createEntry).use { stmt ->
      stmt.setString(1, label)
          stmt.setBigDecimal(2, amount)
          stmt.setBigDecimal(3, fee)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Ledger(
                results.getLong(1),
                results.getString(2),
                results.getBigDecimal(3),
                results.getBigDecimal(4)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun getEntry(id: Long): Ledger? {
    return conn.prepareStatement(getEntry).use { stmt ->
      stmt.setLong(1, id)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Ledger(
                results.getLong(1),
                results.getString(2),
                results.getBigDecimal(3),
                results.getBigDecimal(4)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun listEntries(): List<Ledger> {
    return conn.prepareStatement(listEntries).use { stmt ->

      val results = stmt.executeQuery()
      val ret = mutableListOf<Ledger>()
      while (results.next()) {
          ret.add(Ledger(
                results.getLong(1),
                results.getString(2),
                results.getBigDecimal(3),
                results.getBigDecimal(4)
            ))
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun listEntriesByAmounts(amounts: List<java.math.BigDecimal>): List<Ledger> {
    return conn.prepareStatement(listEntriesByAmounts.replaceFirst("/*SLICE:amounts*/?", if (amounts.isEmpty()) "NULL" else List(amounts.size) { "?" }.joinToString(","))).use { stmt ->
      var i = 1
      for (v in amounts) {
          stmt.setBigDecimal(i, v)
          i++
      }

      val results = stmt.executeQuery()
      val ret = mutableListOf<Ledger>()
      while (results.next()) {
          ret.add(Ledger(
                results.getLong(1),
                results.getString(2),
                results.getBigDecimal(3),
                results.getBigDecimal(4)
            ))
      }
      ret
    }
  }

  @Throws(SQLException::class)
  override fun listEntriesOver(amount: java.math.BigDecimal): List<Ledger> {
    return conn.prepareStatement(listEntriesOver).use { stmt ->
      stmt.setBigDecimal(1, amount)

      val results = stmt.executeQuery()
      val ret = mutableListOf<Ledger>()
      while (results.next()) {
          ret.add(Ledger(
                results.getLong(1),
                results.getString(2),
                results.getBigDecimal(3),
                results.getBigDecimal(4)
            ))
      }
      ret
    }
  }

}

