// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package com.example.numerictest

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

interface Queries {
  @Throws(SQLException::class)
  fun createEntry(
      label: String,
      amount: java.math.BigDecimal,
      fee: java.math.BigDecimal?): Ledger?

  @Throws(SQLException::class)
  fun getEntry(id: Long): Ledger?

  @Throws(SQLException::class)
  fun listEntries(): List<Ledger>

  @Throws(SQLException::class)
  fun listEntriesByAmounts(amounts: List<java.math.BigDecimal>): List<Ledger>

  @Throws(SQLException::class)
  fun listEntriesOver(amount: java.math.BigDecimal): List<Ledger>

}

